### ISSUE TITLE
feat: user data should use raw kubeadm config

### ISSUE THREAD

**Issue by andrewrynhard** [autonomy/dianemo#65]
Currently we use `text/template` to render `MasterConfiguration` and `NodeConfiguration` YAML files that are then fed into `kubeadm`. This is suboptimal since we are duplicating work done in `kubeadm`. We should instead support specifying the files in their raw format:

```yaml
kubernetes:
  kubeadm: |
    kind: NodeConfiguration
    apiVersion: kubeadm.k8s.io/v1alpha1
    token: abcd.1234567898765432
```
